#!/usr/bin/env python3

import argparse
import itertools
import pathlib

from hookinj import gen
from hookinj._make_circuit import make_circuit, CONSTRUCTIONS


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out_dir",
        type=str,
        required=True,
    )
    parser.add_argument("--distance", nargs='+', required=True, type=int)
    parser.add_argument("--memory_rounds", nargs='+', required=True, type=str)
    parser.add_argument("--postselected_rounds", nargs='+', required=True, type=str)
    parser.add_argument("--postselected_diameter", nargs='+', required=True, type=str)
    parser.add_argument("--noise_strength", nargs='+', required=True, type=float)
    parser.add_argument("--noise_model", nargs='+', required=True, choices=['SI1000', 'UniformDepolarizing', 'None'])
    parser.add_argument("--basis", nargs='+', required=True, choices=CONSTRUCTIONS.keys())
    parser.add_argument("--extra", nargs='+', default=(None,))
    parser.add_argument("--extra2", nargs='+', default=(None,))
    parser.add_argument("--extra3", nargs='+', default=(None,))
    parser.add_argument("--convert_to_cz", nargs='+', default=('auto',))
    parser.add_argument("--debug_out_dir", default=None, type=str)
    args = parser.parse_args()

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(exist_ok=True, parents=True)
    debug_out_dir = None
    if args.debug_out_dir is not None:
        debug_out_dir = pathlib.Path(args.debug_out_dir)
        debug_out_dir.mkdir(exist_ok=True, parents=True)

    for (distance,
         noise_strength,
         postselected_rounds_func,
         postselected_diameter_func,
         memory_rounds_func,
         noise_model_name,
         basis,
         extra,
         extra2,
         extra3,
         convert_to_cz_arg) in itertools.product(
            args.distance,
            args.noise_strength,
            args.postselected_rounds,
            args.postselected_diameter,
            args.memory_rounds,
            args.noise_model,
            args.basis,
            args.extra,
            args.extra2,
            args.extra3,
            args.convert_to_cz):
        if noise_model_name == "SI1000":
            noise_model = gen.NoiseModel.si1000(noise_strength)
        elif noise_model_name == "UniformDepolarizing":
            noise_model = gen.NoiseModel.uniform_depolarizing(noise_strength)
        elif noise_model_name == "None":
            noise_model = None
        else:
            raise NotImplementedError(f'{noise_model_name=}')

        postselected_rounds = eval(postselected_rounds_func, {'d': distance})
        postselected_diameter = eval(postselected_diameter_func, {'d': distance})
        memory_rounds = eval(memory_rounds_func, {'d': distance})
        if convert_to_cz_arg == 'auto':
            convert_to_cz = noise_model_name == 'SI1000'
        else:
            convert_to_cz = bool(int(convert_to_cz_arg))
        circuit = make_circuit(
            basis=basis,
            distance=distance,
            noise=noise_model,
            debug_out_dir=debug_out_dir,
            postselected_rounds=postselected_rounds,
            postselected_diameter=postselected_diameter,
            memory_rounds=memory_rounds,
            convert_to_cz=convert_to_cz,
        )
        q = circuit.num_qubits
        extra_tags = ''
        for ex in [extra, extra2, extra3]:
            if ex is not None:
                extra_dict = eval(ex)
                assert isinstance(extra_dict, dict)
                for k, v in extra_dict.items():
                    extra_tags += f',{k}={v}'
        if convert_to_cz:
            extra_tags += ',gates=cz'
        else:
            extra_tags += ',gates=all'
        if 'inject' in basis:
            extra_tags += f',post_q={gen.estimate_qubit_count_during_postselection(circuit)}'
        path = out_dir / f'r={memory_rounds},d={distance},p={noise_strength},noise={noise_model_name},b={basis},post_r={postselected_rounds},post_d={postselected_diameter},q={q}{extra_tags}.stim'
        with open(path, 'w') as f:
            print(circuit, file=f)
        print(f'wrote file://{path.absolute()}')


if __name__ == '__main__':
    main()
